version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phishingdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: ./phishing-simulator-backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: phishingdb
      DB_PORT: 5432
    depends_on:
      - db
  
  frontend:
    build: ./phishing-simulator-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://backend:5000
    depends_on:
      - backend

volumes:
  postgres_data:
